### ISSUE TITLE
Support alternative import / export syntax

### ISSUE THREAD

**Issue by icarito** [metapensiero/metapensiero.pj#39]
I'm trying to use https://nuxtjs.org/examples/auth-routes#using-the-store and I need to produce import statements like these:

```javascript
import Vue from 'vue'
import Vuex from 'vuex'
```

How to achieve this?
Thanks!

**Comment by icarito** [comment]
Also I think related to this is support for `export default` syntax.
The question is how to implement it? If __all__ not a list, perhaps?

**Comment by azazel75** [comment]
so the function/class is accessible at vue.Vue? 

the standard Python's:
```python
from vue import Vue 
```
should work in that case or 
```python 
import vue as Vue
```
if it's a default import:
```bash
$ pj -s -
from vue import Vue
import vue as Vue 

import {Vue} from 'vue';
import * as Vue from 'vue';
```
About the default exports, I simply don't think it's much of a feature.. anywayI've thought about using __all__ too, but  doesn't seem right...

**Comment by icarito** [comment]
I had tried that and I couldn't get it to work but now I learned it was because of an issue with Webpack and module loading https://github.com/webpack/webpack/issues/4039 - apparently you can't mix `import` and `export.modules` so it's a small but important feature.

**Comment by icarito** [comment]
I guess `import {Vue} from 'vue'` is different from `import Vue from 'vue'`.
I was able to get the behaviour I need with `from vue import default as Vue`:
```html
<script lang="py?compiler=pj">
from vue import default as Vue
from vue__codemirror__lite import default as VueCodeMirror

Vue.use(VueCodeMirror)

class Component:
    def __init__(self):
        self['data'] = lambda: { 'code': '2' }
        self['computed'] = { 'data': lambda: 2 }

__all__ = Component()
</script>
```

**Comment by icarito** [comment]
That is after applying patch for default export.

**Comment by azazel75** [comment]
I was wrong, this should be the "non obvious" default import using named imports:
```javascript
import {default as bar} from 'foo';
```

**Comment by azazel75** [comment]
@icarito  Please see the referenced commit and see if it now works for you!

**Comment by azazel75** [comment]
I still have to update the docs

**Comment by icarito** [comment]
Thanks for your updates! Also I suggest to implement anonymous default export as in https://gitlab.com/metapensiero/metapensiero.pj/merge_requests/35

**Comment by azazel75** [comment]
Hi @icarito, I'm closing this. It seems superseded by the changes in the repo. Open a new one for any remaining issues. Also note that i've made a new release, so you don't have to refer directly to a snapshot of the repo in your requirements.txt
