### ISSUE TITLE
Cant install javascripthon

### ISSUE THREAD

**Issue by M0n7y5** [metapensiero/metapensiero.pj#44]
Installing javascripthon via pip is followed by this error

```python
Collecting javascripthon
  Using cached javascripthon-0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Of3AfA/javascripthon/setup.py", line 14, in <module>
        with open(os.path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Of3AfA/javascripthon/```

**Comment by azazel75** [comment]
Hi @M0n7y5, which python version are you using? Javascripthon works with Python 3.5+

**Comment by M0n7y5** [comment]
Hi @azazel75, Python 3.6.1

**Comment by azazel75** [comment]
@M0n7y5, I don't think so, maybe you have it installed (if it's a linux distribution probably it's called `python3`) but you aren't using  it to install Javascripthon. Probably you are using an old python 2.x. That error cannot happen in 3.6, see  https://docs.python.org/3.5/library/functions.html#open

**Comment by azazel75** [comment]
So? any news here?

**Comment by azazel75** [comment]
ok then, I'll close it

**Comment by AnonymousSB** [comment]
For those of us on Mac, where it comes with python 2.7 installed, you can install python3, but `pip install javascripthon` will still fail. You can specify to install javascripthon using python3 with the following command.

```
python3 -m pip install javascripthon
```
