### ISSUE TITLE
When would the master branch be released?

### ISSUE THREAD

**Issue by chfw** [metapensiero/metapensiero.pj#45]
Hi all,

Thanks for your great work to blur the boundary of python and javascript. We are using it to [transcompile python functions into javascript functions](https://github.com/pyecharts/pyecharts/pull/468). Now we [got a problem](https://ci.appveyor.com/project/chenjiandongx/pyecharts/build/1.0.336/job/h7lu9re79r1bj6tj#L284) with windows machines, where Microsoft prefer '\\' over '/'. However, [the path separator problem have been nicely fixed on master branch](https://github.com/metapensiero/metapensiero.pj/blob/master/src/metapensiero/pj/processor/util.py#L54) and our build [passed](https://ci.appveyor.com/project/chenjiandongx/pyecharts/build/job/exxa8lm6tkyixfcu) if we use your master branch. So could you please share your time schedule for your next release?.

Thanks.

**Comment by azazel75** [comment]
Hi @chfw, 
nice to know that it is useful to someone! My chinese is a bit rusty btw ;-) 
I didn't had any reason to rush a release because I was thinking that no one used it and also because I'm  slowly working on some new features in another branch. 

Anyway, if you need it I can release soon after I checked that all the features/changes  are documented.

**Comment by chfw** [comment]
Yep, definitely we need your next release sooner. Then we will release ours. 

After our next release, I would imagine your library will be used not only by our small open source team, but by at least a few thousands of data engineers/scientists/amateurs.

**Comment by azazel75** [comment]
So, I've released the 0.9 release, let me know if it works as expected

**Comment by chfw** [comment]
version 0.9 [works like a charm](https://ci.appveyor.com/project/chenjiandongx/pyecharts/build/job/a18t6hb1md6c9bbx). Superb support!

Please anticipate more issues will be coming from pyecharts community as we are forging our next major release 0.5.0, which is first ever release that mixes python function into javascript runtime. 👍

**Comment by chfw** [comment]
for your information, this is how pyecharts brings your project to python 2.7 and 3.4 users.

https://github.com/pyecharts/pyecharts-javascripthon-api-service

**Comment by azazel75** [comment]
Nice, but how you deal with python code differences, e.g. the `print` being a statement in python 2 and a function in python 3?

**Comment by azazel75** [comment]
>>>>> "jaska" == jaska  <notifications@github.com> writes:

    jaska> Yes, you are absolutely right. Meanwhile, we do not want left
    jaska> our python 2.7 users behind. So here is what I noted about
    jaska> the usage: ``` Usage

    jaska> 1. Only Python 3.5+ code can be transcompiled. If you use python 2.7
    jaska> or 3.4, you are obliged to use generic Python codes so that python 2.7
    jaska> and 3.4 interpreter do not complain.
    jaska> ```

I see 

    jaska> With the experimental api service, pyecharts-javascripthon passes very
    jaska> basic unit test on [2.7 and
    jaska> 3.4](https://travis-ci.org/pyecharts/pyecharts-javascripthon). Issues
    jaska> will come from 2.7 and 3.4 users but let them try first. pyecharts
    jaska> community are very excited about the javascript callback function
    jaska> support, which will enable them to draw more complicated charts.

:-)

I'm wondering if the 2-to-3 automatic conversion tool can be of any
help... I'll give some more thinking to it. By the way, Py 3.4 code is
not a problem, it's just its reprhesentation in 3.4 ast that's a
problem.

well done! I'm eager to see new bugs report coming in ;-)
-- 
Alberto Berti -  Information Technology Consultant

"gutta cavat lapidem"
