### ISSUE TITLE
Try to debug and contribute but Failed

### ISSUE THREAD

**Issue by yemingyu** [metapensiero/metapensiero.pj#52]
yeyupro:metapensiero yemingyu$  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pj.__main__  -d -s '"foo" if True else "bar"'

Namespace(debug=True, dump_ast=False, es5=False, es6=True, eval=False, files=[], inline_map=False, output=None, pdb=False, source_name=None, stage3=True, string='"foo" if True else "bar"', truntime=False)
DEBUG:__main__:Log started
INFO:macropy.core.import_hooks:Expand macros in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/metapensiero/pj/transformations/classes.py
INFO:macropy.core.macros:Finding macros in 'metapensiero.pj.transformations.classes'
INFO:macropy.core.macros:Importing macros from 'macropy.core.quotes' into 'metapensiero.pj.transformations.classes'
INFO:macropy.core.macros:Importing macros from 'macropy.experimental.pattern' into 'metapensiero.pj.transformations.classes'
INFO:macropy.core.import_hooks:Expand macros in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/macropy/experimental/__init__.py
INFO:macropy.core.macros:Finding macros in 'macropy.experimental'
INFO:macropy.core.import_hooks:Expand macros in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/macropy/experimental/pattern.py
INFO:macropy.core.macros:Finding macros in 'macropy.experimental.pattern'
INFO:macropy.core.macros:Importing macros from 'macropy.core.quotes' into 'macropy.experimental.pattern'
INFO:macropy.core.macros:Importing macros from 'macropy.core.hquotes' into 'macropy.experimental.pattern'
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 266
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 268
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 270
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 273
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 275
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 280
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 287
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 299
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 308
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 310
DEBUG:macropy.core.macros:Found macro 'hq', type 'Block', line 333
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 336
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 342
DEBUG:macropy.core.macros:Found macro 'hq', type 'Expr', line 395
DEBUG:macropy.core.macros:Found macro 'q', type 'Block', line 255
DEBUG:macropy.core.macros:Found macro 'switch', type 'Block', line 393
DEBUG:macropy.core.macros:Found macro 'q', type 'Expr', line 395
DEBUG:macropy.core.macros:Found macro 'q', type 'Expr', line 402
DEBUG:macropy.core.macros:Found macro 'q', type 'Expr', line 405
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/yemingyu/TranslatorUtil/metapensiero.pj/src/metapensiero/pj/__main__.py", line 266, in <module>
    main()
  File "/Users/yemingyu/TranslatorUtil/metapensiero.pj/src/metapensiero/pj/__main__.py", line 163, in main
    res = transform_string(input, es5, es6, stage3,
  File "/Users/yemingyu/TranslatorUtil/metapensiero.pj/src/metapensiero/pj/__main__.py", line 112, in transform_string
    res, src_map = api.translates(input, enable_es6=enable_es6,
  File "/Users/yemingyu/TranslatorUtil/metapensiero.pj/src/metapensiero/pj/api.py", line 167, in translates
    src_map = js_code_block.sourcemap(complete_src or src_text, src_filename,
  File "/Users/yemingyu/TranslatorUtil/metapensiero.pj/src/metapensiero/pj/processor/util.py", line 377, in sourcemap
    for m in self.src_mappings(src_offset, dst_offset):
  File "/Users/yemingyu/TranslatorUtil/metapensiero.pj/src/metapensiero/pj/processor/util.py", line 363, in src_mappings
    for m in line.src_mappings():
  File "/Users/yemingyu/TranslatorUtil/metapensiero.pj/src/metapensiero/pj/processor/util.py", line 264, in src_mappings
    assert isinstance(self.item, Part)
AssertionError

**Comment by azazel75** [comment]
Could you please elaborate a bit more on this and tell me which version of Javascrypthon do you have installed and what's your o.s.?

thanks

**Comment by yemingyu** [comment]
> Could you please elaborate a bit more on this and tell me which version of Javascrypthon do you have installed and what's your o.s.?
> 
> thanks

Hi, I have temporarily bypassed the above question.
There is an additional problem, --dump-ast does not take effect.
Env：MACOS 10.15.5 、python 3.8、Javascrypthon 0.11
