### ISSUE TITLE
Fails on simple byte sequence: ValueError: Unknown data type received.

### ISSUE THREAD

**Issue by exander77** [metapensiero/metapensiero.pj#57]
Input:
```
a = b'\x00'
```

**Comment by azazel75** [comment]
yeah, I didn't need any bytes in JS, so I did not add support for it

**Comment by exander77** [comment]
JavaScript has native ByteBuffers. Without this, basically no encryption, binary data manipulation etc. cannot be implemented.

**Comment by azazel75** [comment]
PRs are accepted (with tests)
