### ISSUE TITLE
Problems when translating class

### ISSUE THREAD

**Issue by streetartist** [metapensiero/metapensiero.pj#64]
When transferring a class, the operation of generating a class instance is treated as a calling function, and a type check should be added to avoid this problem
```python
a = aclass()
```
Translated into
```javascript
a = aclass();
```

**Comment by azazel75** [comment]
Hi @streetartist, as written in the README, the rule is as follows:
```python
FirstCharCapitalized(...)
new(any_function(...))
```
translates into:
```Javascript
new FirstCharCapitalized(...)
new any_function(...)
```

**Comment by streetartist** [comment]
Thanks
