### ISSUE TITLE
Nested classes?

### ISSUE THREAD

**Issue by brianwawok** [metapensiero/metapensiero.pj#66]
Trying to use django-enumfields with this project  (https://github.com/hzdg/django-enumfields).  The syntax to override a field label is a nested class. Example enum:

```
import enumfields


class Test(enumfields.IntEnum):
    FIRST = 1
    SECOND = 2
    
    class Labels:
        FIRST = 'fIrSt'
```

The error is something like

**UnsupportedSyntaxError: Node type 'ClassDef': Line: 4, column: 0. Class' body members must be functions or assignments**

Torn between trying to make the syntax less crazy on the enumfields, vs some kind of super super limited nested class support. This is pure syntatic sugar, and not necessary.. expect for it is how this code runs. If you look at what labels is actually doing, it's not much.. ( https://github.com/hzdg/django-enumfields/blob/master/enumfields/enums.py)

**Comment by azazel75** [comment]
Hi @brianwawok , there two things here to note.

The first is probably a misunderstanding and maybe it's not clear from the readme, but this library is to convert Python modules to JS and its libraries, so in your case the library you import has to be a JS library or another converted module. So in your case the django library imported will never be converted.

The second thing is what the error message states: it's really a limitation of JS classes which are the target of the translation of Python classes.

I hope it's more clear now

**Comment by brianwawok** [comment]
@azazel75 Tell me more, why would Python never be converted?  If I remove my nested subclass, this correctly coverts to JS.  If you look at what is going on under the hood, I don't think there is actually any reason this subset of inner classes could not translate to JS...

**Comment by azazel75** [comment]
So this is how the code gets translated without the inner class:
```
$ pj -s -
import enumfields


class Test(enumfields.IntEnum):
    FIRST = 1
    SECOND = 2

import * as enumfields from 'enumfields';
var _pj;
function _pj_snippets(container) {
    function set_properties(cls, props) {
        var desc, value;
        var _pj_a = props;
        for (var p in _pj_a) {
            if (_pj_a.hasOwnProperty(p)) {
                value = props[p];
                if (((((! ((value instanceof Map) || (value instanceof WeakMap))) && (value instanceof Object)) && ("get" in value)) && (value.get instanceof Function))) {
                    desc = value;
                } else {
                    desc = {"value": value, "enumerable": false, "configurable": true, "writable": true};
                }
                Object.defineProperty(cls.prototype, p, desc);
            }
        }
    }
    container["set_properties"] = set_properties;
    return container;
}
_pj = {};
_pj_snippets(_pj);

class Test extends enumfields.IntEnum {
}
_pj.set_properties(Test, {"FIRST": 1, "SECOND": 2});
```

Now, this expects to import an `enumfields` symbol from and "enumfield"  JS library  to later use it  as the base for your Test class, which simply isn't there and isn't going to work.

If you just have to share data, you will have more success by writing a small fragment of JSON into the rendered page and assingn it to the window object.

**Comment by brianwawok** [comment]
Boo, did not see the import failing there too. Yah that might be too much.

I will likely just write a manual really limited version of metapensiero that just knows how to translate enums. 

Bah was a fun pipe dream while it lasted ;)
