### ISSUE TITLE
Is the project maintained? 

### ISSUE THREAD

**Issue by Shahin-rmz** [metapensiero/metapensiero.pj#67]
Hello, the project seems to be a dream.
As you know, python lacks in front end web development part.
There is a new declarative, JavaScript frontend compiler, which is named Svelte.

I was thinking if we could write the script part of the svelete with python and converts it to JavaScript and have frontend.

**Comment by azazel75** [comment]
Hi  Shanin, 

do you have any example of what you want to obtain?

**Comment by Shahin-rmz** [comment]
@azazel75 ,thanks for reply.
I will make an example and head back to you.
I'm not familiar with JS, so try to figure svelte out.

**Comment by Shahin-rmz** [comment]
@azazel75 [Here](https://svelte.dev/examples/event-modifiers) is a link of an example in Svelte.
I write it in both JS and Python.
```JavaScript
<script>
	function handleClick() {
		alert('no more alerts')
	}
</script>

<button on:click|once={handleClick}>
	Click me
</button>
```

what I want is following:

```Python
<script>
    def handleClick():
        print('no more alerts')
</script>

<button on:click|once={handleClick}>
	Click me
</button>
```

**Comment by azazel75** [comment]
You just have to move the code to an external file that is built from a python source and you have it
