### ISSUE TITLE
Support for comments

### ISSUE THREAD

**Issue by sierret** [metapensiero/metapensiero.pj#77]
Comments currently don't seem supported. Appear to be omitted outright in output. I snooped around a bit and I see the ast package you use has an version that supports comments called ast-comments. Seems simple to install and replace:

`import ast`

with

`import ast_comments as  ast`

so as to avoid excessive refactoring. However, further than this I'm unsure/confused how code transformation works under the hood to allow ast comments to actually be converted to js comments and be included in output. Could you look into this. It *seems* fairly simple to add.

**Comment by azazel75** [comment]
I don't understand, what do you mean that comments are unsupported? They don't get translate into JS comments, no.... As code isn't a line-per-line translation I don't know if it has any sense at all... I'm not very interested in it.  PR are welcome!

**Comment by sierret** [comment]
Oh I think I understand. Yes, I thought it was line by line. Ok understood. I will mark as solved then.
