### ISSUE TITLE
AssertionError on complex list index

### ISSUE THREAD

**Issue by System25** [metapensiero/metapensiero.pj#78]
Hi, when I try to transpile from Python to Javascript and the list index is slightly complex (or a negative number) an AssertionError is produced without any more information (line number is nor shown in the error message).

So, the following code fails to transpile:
`if f.statements[-1].code.name == 'exit':`

The following code also fails to transpile:
`if f.statements[len(f.statements)-1].code.name == 'exit':`

The following code works fine:
```
last = len(f.statements)-1
if f.statements[last].code.name == 'exit':
```

Thanks

**Comment by TEParsons** [comment]
This also happens when an index is a value in another array, e.g. `a[b[0]]`

**Comment by azazel75** [comment]
I'm kinda surprised that there are people still using pj, mostly after the release of webassembly compiled python...
